<?=$this->pageLocation()?>
<div id="view-content">
    <div id="sub-menu">
        <a href="/form/add/target/todo-list">新增項目</a>
     <?php if($this->request->getParam('history')===null){ ?>    
        <a href="?history">歷史項目</a>
     <?php }else{ ?>
        <a href="/form/todo-list/">現有項目</a>
     <?php } ?>   
    </div>
    <form id="frm_sortable" name="frm_sortable">
        <table width="100%">
            <tbody id="sortable">
                <tr>
                    <th width="50">編號</th>
                    <th>標題</th>
                    <th width="50">&nbsp;</th>
                </tr>
            <?php
            if($this->data !=null){
                foreach($this->data as $idx=>$obj){    
            ?>
            <!--   有記錄時顯示    --> 
                <tr>
                    <td style="text-align:center"><span class="serial" ><?=($idx+1)?></span></td>
                    <td>
                        <a href="/form/update/target/todo-list/id/<?=$obj->getId()?>"><?=$obj->getTitle()?></a>
                        <? if($obj->getDone()){ ?>(<?=$obj->getDone()?>)<? } ?>
                        <input type="hidden" name="id[]" value="<?=$obj->getId()?>"/>
                    </td>
                    <td><?php if(!$obj->getDone()){ ?><a class="todo-done" href="javascript:" hook="<?=$obj->getId()?>">完成</a><? } ?></td>
                </tr>
            <!--   有記錄時顯示    -->
                <?php
                }
            }else{
            ?>
            <!-- 沒有記錄時顯示 -->
                <tr>
                    <td colspan="2">目前沒有任何記錄</td>
                </tr>
            <!-- 沒有記錄時顯示 -->
            <?php
            }
            ?>
            </tbody>
        </table>
    </form>
    <div id="pager"><?=$this->pager?></div>
</div>