CREATE TABLE `order_item` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`order_id` INT UNSIGNED NOT NULL ,
`item` VARCHAR( 255 ) NOT NULL ,
`amount` INT UNSIGNED NOT NULL ,
`unit_price` INT UNSIGNED NOT NULL ,
`summary` INT UNSIGNED NOT NULL ,
`comment` TEXT NULL ,
INDEX ( `order_id` )
) ENGINE = MYISAM ;