<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <link href="/style/login.css" rel="stylesheet" type="text/css" />
  <?=$this->headScript()?>
  <?=$this->headStyle()?>
  <title><?=$this->layout()->pageTitle?></title>
  </head>
  <body>
      <div id="header"><h3><a href="/"><?=$this->layout()->pageTitle?></a></h3></div>
      <div id="mainBox">
            <div id="contentBox"><?=$this->layout()->content?></div>    
      </div>      
  </body>
</html>

