<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="generator" content="PSPad editor, www.pspad.com">
  <link href="/style/style.css" rel="stylesheet" type="text/css" />
  <link href="/style/jquery-ui-1.8.16.custom.css" rel="stylesheet" type="text/css"/>
  <script type="text/javascript" src="/javascript/jquery-1.6.2.min.js"></script>
  <?=$this->headScript()?>
  <?=$this->headStyle()?>
  <title><?=$this->layout()->pageTitle?></title>
  </head>
  <body>
      <div id="header"><h3><a href="/"><?=$this->layout()->pageTitle?></a></h3></div>
      <div id="mainBox">
            <div id="menuBox">
                   <span class="menuTitle">帳號操作</span>
                       <span class="menuItem">帳號：<?=$this->identity->account?></span>
                       <span class="menuItem">名稱：<?=$this->identity->username?></span>
                       <a href="/index/logout/">登出</a>
                <?php foreach($this->layout()->menu as $menuItem){ ?>
                   <span class="menuTitle"><?=$menuItem['subject']?></span>
                   <?php foreach($menuItem['sub'] as $item){ ?>                   
                       <a href="<?=$item['op']?>"><?=$item['name']?></a>
                   <?php } ?>
                <?php } ?>
            </div>
            <div id="contentBox"><?=$this->layout()->content?></div>    
      </div>
      
  </body>
</html>

