<?=$this->pageLocation()?>
<div id="view-content">
  <?=$this->SubMenu()?>
  <!--<table>
	   <tr>
	      <th>項目編號</th><th>項目名稱</th>
	   </tr>-->
<form id="ajaxfrm">
	<div id="sortable">   
 <?php
   if(!empty($this->checkitems)){
      foreach($this->checkitems as $k=>$row){
 ?>
    <div class="float-object">
       <span class="key"><?=$row['id']?></span><span class="name"><a href="/admin/update/target/checkitem/id/<?=$row['id']?>"><?=$row['item']?></a></span>
       <input type="hidden" name="id[<?=$k?>]" value="<?=$row['id']?>"/>
    </div>
 <?php
      }
   }
 ?>	   
	<div style="clear:both"></div>
	</div>
</form>	
	<?=$this->inlineScript()?>
  <!--</table>-->
</div>