<form action="" method="post">
姓名：<input type="text" name="name" value="<?=$this->data->name?>" size="30"/><span class="valid_error"><?=$this->errorMessages['name']?></span><br/>
電話：<input type="text" name="phone" value="<?=$this->data->phone?>" size="30"/><span  class="valid_error"><?=$this->errorMessages['phone']?></span><br/>
手機：<input type="text" name="mobile" value="<?=$this->data->mobile?>" size="30"/><span  class="valid_error"><?=$this->errorMessages['mobile']?></span><br/>
地址：<input type="text" name="address" value="<?=$this->data->address?>" size="50"/><span class="valid_error"><?=$this->errorMessages['address']?></span><br/>
公司名稱：<input type="text" name="company" value="<?=$this->data->company?>" size="30"/><span class="valid_error"><?=$this->errorMessages['company']?></span><br/>
email：<input type="text" name="email" value="<?=$this->data->email?>" size="30"/><span class="valid_error"><?=$this->errorMessages['email']?></span><br/>
生日：<input type="text" name="birthday" value="<?=$this->data->birthday?>" size="30"/><span class="valid_error"><?=$this->errorMessages['birthday']?></span><br/>
車輛數:<?=$this->data->getOwnedCarNums()?><br/>
<input type="hidden" name="id" value="<?=$this->data->id?>">
<input type="submit" name="button-submit"  value="更新"/>
</form>
