<form action="" method="post">
名稱：<input type="text" name="name" value="<?=$this->errorData['name']?>" size="30"/><span class="valid_error"><?=$this->errorMessages['name']?></span><br/>
聯絡人：<input type="text" name="contact" value="<?=$this->errorData['contact']?>" size="30"/><span class="valid_error"><?=$this->errorMessages['contact']?></span><br/>
電話：<input type="text" name="phone" value="<?=$this->errorData['phone']?>" size="30"/><span class="valid_error"><?=$this->errorMessages['phone']?></span><br/>
手機：<input type="text" name="mobile" value="<?=$this->errorData['mobile']?>" size="30"/><span class="valid_error"><?=$this->errorMessages['mobile']?></span><br/>
地址：<input type="text" name="address" value="<?=$this->errorData['address']?>" size="30"/><span class="valid_error"><?=$this->errorMessages['address']?></span><br/>
email：<input type="text" name="email" value="<?=$this->errorData['email']?>" size="30"/><span class="valid_error"><?=$this->errorMessages['email']?></span><br/>
<input type="submit" name="button-submit"  value="新增"/>
</form>