<?=$this->pageLocation()?>
<div id="view-content">
  <?=$this->SubMenu()?>
	<form  id="supplier_list_frm" action="/admin/delete/target/supplier" method="post">
  <table style="width:100%">
	   <tr>
         <th><input type="checkbox" id="multi_check"/></th>
         <th>廠商名稱</th>
         <th>聯絡人</th>
         <th>電話</th>
         <th>手機</th>
         <th>地址</th>         
         <th>email</th>         
     </tr>
  <?php
     if(count($this->supplierArray)>0){
        foreach($this->supplierArray as $supplier){
  ?>
     <tr>
         <th><input type="checkbox" name="delete[]" value="<?=$supplier->id?>"/></th><!-- style="text-align:center"-->
         <td><a href="/admin/update/target/supplier/id/<?=$supplier->id?>"><?=$supplier->name?></a></td>
         <td><?=$supplier->contact?></td>          
         <td><?=$supplier->phone?></td>
         <td><?=$supplier->mobile?></td>
         <td><?=$supplier->address?></td>         
         <td><?=$supplier->email?></td>         
     </tr>
  <?php
        }
     }else{     
  ?>
     <tr>
        <td colspan="7">目前沒有任何記錄</td>
     </tr>
  <?php
     }
  ?>   
	</table>
	<input type="button" id="delete_smt" name="delete_smt" value="刪除"/>
	<?=$this->inlineScript()?>
	</form>
	<div id="pager"><?=$this->pageController?></div>
</div>